# Site settings
title: Ondt blod brewery
email: orkjern@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ondt blod brewery. Stats and recipes.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/brew/:year/:month/:day/:title.html"
url: "https://ondtblod.github.io" # the base hostname & protocol for your site
exclude: [node_modules, package.json, bower_components]

# Build settings
markdown: kramdown
# Prose
prose:
  rooturl: '_posts'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "category"
        field:
          element: "hidden"
          value: "post"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: published
        field:
          element: checkbox
          label: Published
          value: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
