# Site settings
title: Ondt blod brewery
email: orkjern@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ondt blod brewery. Stats and recipes.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/brew/:year/:month/:day/:title.html"
url: "https://ondtblod.github.io" # the base hostname & protocol for your site
exclude: [node_modules, package.json, bower_components]

# Build settings
markdown: kramdown
